### ISSUE TITLE
Questions about the training dataset and model training 

### ISSUE THREAD

**Issue by HelenYSLin** [quansun98/GAUDI#1]
Hi, I have two questions before and while running GAUDI:

1. I wanted to clarify the definition of the training dataset. It's a bit ambiguous for me whether "discovery" samples and "training" samples are considered equivalent in GAUDI. For example, if I have external GWAS results as discovery data from one site, do I also need the individual-level data from the site as training samples, or are both training and testing samples referred to samples split in the "target" dataset from another site?

2. I was running GAUDI using the toy dataset provided in this tool. At the model training step, I was able to reach Fitting fold 5 but then got an error. I used the following script exactly as shown in the tutorial:
```
Rscript fit_cv_fused_lasso.R \
	--gaudi-path . \
	--gwas data/GWAS_chr22_sim.regenie \
	--gwas-col-id ID --gwas-col-p LOG10P --gwas-log-p TRUE \
	--la data/test_out_allChr.la_dosage.mtx.gz \
	--col data/test_out_allChr.la_dosage.colnames \
	--row data/test_out_allChr.la_dosage.rownames \
	--pheno data/test.pheno --pheno-name pheno --pheno-iid FID \
	--start-p-exp -1 --end-p-exp -5 \
	--seed 2022 --sparsity FALSE \
	--out data/test_p1_5_model
```
Below is the error I encountered:
```
Error in if (!is.na(p_fits[[i]])) { : the condition has length > 1
In addition: There were 12 warnings (use warnings() to see them)
Execution halted
```
What might be the issue here? Looking forward to your solution.

**Comment by quansun98** [comment]
Hi, thanks for your interests in our method and for the questions. 

1. That's a good question. First, GAUDI is an individual-level data method, which requires genotypes and local ancestries for training the models. Although it has a GWAS summary statistics flag to run the script, it only uses the GWAS p-values for variant screening/filtering purpose. Thus, you can use any external GWAS summary statistics for "discovery" to tell GAUDI the marginal association p-values you would like to use for variant filtering. Then you will need another set of individuals (with genotypes available) to train the model. The two ways you mentioned in your case both could work, and it depends on your purpose (and data availability) to choose which way to go. In our experience, the latter (training and testing in your "target" from another site) will likely produce more accurate models due to similar admixture and less confounding effects using data from the same site. Please let me know if I am clear. 

2. It looks like the error is that `if(!is.na(p_fits[[i]]))` received a vector with more than one value, but `p_fits[[i]]` should not be a vector, as long as `i` is a single value. I would check the value of `i` to see what it is, and run the `if()` command directly. Btw, I just tried running the tutorial from another directory and it went smoothly. Do you mind trying running again to see if it still happens? 

Thanks!

**Comment by HelenYSLin** [comment]
Thanks for your explanation for the first question!

I tried to reinstall GAUDI and ran it again, but the same error still showed up. Perhaps something wrong in the earlier stpes? I can show you the results of the previous steps to see when this problem starts to occur -

```
while read chunk; do
	start_pos=$(( ($chunk - 1)*10*1000000 ))
	end_pos=$(( ($chunk)*10*1000000 ))
	./py_vcf_to_la.py \
		--local-ancestry ~/GAUDI/data/local_anc_chr22.msp.tsv.gz \
		--vcf ~/GAUDI/data/test_chr22.vcf.gz \
		--include ~/GAUDI/data/chr22_minMAF0.001_Rsq0.9_GWASp0.05.txt \
		--la-dosage-threshold 5 \
		--chr 22 --pos-start $start_pos --pos-stop $end_pos \
		--out data/test_out_chr22_chunk${chunk}
done < <( awk -v chr=$chr '$1==chr { print $2 }' data/chunk_list)
```
Nothing appeared on the command line after running this chunk of code. The only file with the prefix `test_out_chr22_chunk` that was generated (or already existed) was `test_out_chr22_chunk1.la_dosage.tsv.gz`. Is this the correct and only output for this step?

And then I ran this: 
`Rscript merge_la_dosage.R data`

Here is the log:
```
── Attaching core tidyverse packages ─────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ───────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package to force all conflicts to become errors

Attaching package: ‘data.table’

The following objects are masked from ‘package:lubridate’:

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year

The following objects are masked from ‘package:dplyr’:

    between, first, last

The following object is masked from ‘package:purrr’:

    transpose


Attaching package: ‘Matrix’

The following objects are masked from ‘package:tidyr’:

    expand, pack, unpack

[1] 1
[1] "Reading file test_out_chr22_chunk1.la_dosage.tsv.gz"
[1] 1
No la dosage files for chr 1
[1] 2
No la dosage files for chr 2
[1] 3
No la dosage files for chr 3
[1] 4
No la dosage files for chr 4
[1] 5
No la dosage files for chr 5
[1] 6
No la dosage files for chr 6
[1] 7
No la dosage files for chr 7
[1] 8
No la dosage files for chr 8
[1] 9
No la dosage files for chr 9
[1] 10
No la dosage files for chr 10
[1] 11
No la dosage files for chr 11
[1] 12
No la dosage files for chr 12
[1] 13
No la dosage files for chr 13
[1] 14
No la dosage files for chr 14
[1] 15
No la dosage files for chr 15
[1] 16
No la dosage files for chr 16
[1] 17
No la dosage files for chr 17
[1] 18
No la dosage files for chr 18
[1] 19
No la dosage files for chr 19
[1] 20
No la dosage files for chr 20
[1] 21
No la dosage files for chr 21
[1] 22
NULL
data/test_out_allChr.la_dosage.mtx.gz already exists -- do you wish to overwrite (y or n)?
```
I then entered "y". Is `test_out_allChr.la_dosage.mtx.gz`the expected output?

Then the next chunk of code is the one in my original post
I can post the log before reaching the error if that would be helpful, but it's just a bit long.

**Comment by quansun98** [comment]
I think it's the R version issue... same error happened to me using a newer R version. Just fixed the bug now, please re-download and give it a try. Sorry for the hassle and thanks for letting me know!

**Comment by HelenYSLin** [comment]
It works now! Thanks so much for fixing it.
